//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Provincia
    {
        public string Codigo { get; set; }
        public string Descripcion { get; set; }
        public string Descripcion_Abrv { get; set; }
        public string Codigo_Pais { get; set; }
        public string Codigo_Departamento { get; set; }
        public string Estado { get; set; }
        public string Usuario_Registro { get; set; }
        public Nullable<System.DateTime> Fecha_Registro { get; set; }
    }
}
